name: base
lendMarket:
  - protocol: aave
    healthFactorLimit: 3
    collaterals:
      - symbol: eth
        autosupplyAmount: 0.9
      - symbol: usdc
        autosupplyAmount: 1800
    tokens:
      - symbol: eth
        minRepay: 0.1
        minReserved: 0
